ar-extensions/ruby/1.9.1/gems/monologue-0.2.0/config/routes.rb
Monologue::Engine.routes.draw do
  root :to =>  "posts#index"
  match "/page/:page", :to =>  "posts#index", :as =>  "posts_page"
  match "/feed" => "posts#feed", :as =>  "feed", :defaults => {:format => :rss}

  match "/tags/:tag" =>"tags#show", :as => "tags_page"

  namespace :admin, :path => "monologue" do
    get "/" => "posts#index", :as =>  "" # responds to admin_url and admin_path
    get "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    resources :sessions
    resources :posts
    resources :users
    get "comments" => "comments#show", :as => "comments"

    get "cache" => "cache#show", :as => "cache"
    delete "cache" => "cache#destroy"
  end

  match "*post_url" => "posts#show", :as =>  "post"
end

ar-extensions/ruby/1.9.1/gems/monologue-0.2.0/app/controllers/monologue/admin/cache_controller.rb
class Monologue::Admin::CacheController < Monologue::Admin::BaseController
  before_filter :prepare_file_list

  def show
    if ActionController::Base.perform_caching && Monologue::PageCache.enabled && Monologue::PageCache.wipe_enabled &&  ActionController::Base.page_cache_directory != Rails.public_path
      render :show
    else
      render :how_to_enable
    end
  end

  def destroy
    Monologue::TotalSweeper.wipe_all
    flash.notice = I18n.t("monologue.admin.cache.show.cache_wiped")
    render :show
  end

  private
  def prepare_file_list
    @files = []
    Dir.glob("#{ActionController::Base.page_cache_directory}/**/*").each do |file|
      next if File.directory?(file)
      @files << file.gsub(ActionController::Base.page_cache_directory,"")
    end
    @files
  end
end

ar-extensions/ruby/1.9.1/gems/monologue-0.2.0/app/views/monologue/admin/cache/_config.html.erb
<h1>Current config</h1>
<p>Want to know more about those configs? See here: <%= link_to "Configure Monologue's cache (english only)", "https://github.com/jipiboily/monologue/wiki/Configure-Monologue's-cache", :target => "_blank" %></p>

<div class="alert alert-<%= ActionController::Base.perform_caching ? "success" : "error" %>">
  ActionController::Base.perform_caching = <%= ActionController::Base.perform_caching %>
</div>

<div class="alert alert-<%= ActionController::Base.page_cache_directory != Rails.public_path ? "success" : "error" %>">
  ActionController::Base.page_cache_directory = <%= ActionController::Base.page_cache_directory %>
</div>

<div class="alert alert-<%= Monologue::PageCache.enabled ? "success" : "error" %>">
  Monologue::PageCache.enabled = <%= Monologue::PageCache.enabled %>
</div>

<div class="alert alert-<%= Monologue::PageCache.wipe_enabled ? "success" : "error" %>">
  Monologue::PageCache.wipe_enabled = <%= Monologue::PageCache.wipe_enabled %>
</div>

ar-extensions/ruby/1.9.1/gems/monologue-0.2.0/app/views/monologue/admin/cache/how_to_enable.html.erb
<div class="alert alert-block">
  <h4><%= t(".warning") %></h4>
  <%= t(".explanations") %>
</div>

<%= render "config" %>

ar-extensions/ruby/1.9.1/gems/monologue-0.2.0/app/views/monologue/admin/cache/show.html.erb
<h1><%= t(".title") %></h1>

<p><%= t(".description") %></p>

<hr>

<h2><%= t(".delete") %></h2>
<%= link_to t(".delete"), admin_cache_path, :data => {:confirm => t(".confirm")}, :method => :delete, :class => "btn btn-large btn-danger" %>

<hr>

<h2><%= t(".files_in_cache") %></h2>
<% if @files.any? %>
  <ul>
    <% @files.each do |file| %>
      <% next if File.directory?(file) %>
      <li><%= file.gsub(ActionController::Base.page_cache_directory,"") %></li>
    <% end %>
  </ul>
<% else %>
  <p><%= t(".no_files_are_cached") %></p>
<% end %>

<hr>

<%= render "config" %>