config/routes.rb
WebCrawler::Application.routes.draw do


  
  
  resources :posts, :path => "/blog"

  resources :searches do
    member { post :deliver}
  end

  #ActiveAdmin.routes(self)

  devise_for :users, #path_names: {sign_in: "login", sign_out: "logout"},
                   :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :users do get'/users/sign_out' => 'devise/sessions#destroy' end
  
  #get "search/search"

  get 'search' => 'search#search', :as => 'search'

  resources :jobs do#, :path => '' do
    resources :jobapps, :shallow => true#,:path => ''
  end

  resources :jobs do
    resources :messages
  end

  resources :jobapps, :only => [:index]
  
  resources :base_urls

  root :to => "search#search"
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/base_urls_controller.rb
class BaseUrlsController < ApplicationController
  # GET /base_urls
  # GET /base_urls.json
  load_and_authorize_resource

  def index
    @base_urls = BaseUrl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @base_urls }
    end
  end

  # GET /base_urls/1
  # GET /base_urls/1.json
  def show
    @base_url = BaseUrl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @base_url }
    end
  end

  # GET /base_urls/new
  # GET /base_urls/new.json
  def new
    @base_url = BaseUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @base_url }
    end

  end

  # GET /base_urls/1/edit
  def edit
    @base_url = BaseUrl.find(params[:id])
  end

  # POST /base_urls
  # POST /base_urls.json
  def create
    @base_url = BaseUrl.new(params[:base_url])

    respond_to do |format|
      if @base_url.save
        format.html { redirect_to @base_url, notice: 'Base url was successfully created.' }
        format.json { render json: @base_url, status: :created, location: @base_url }      
      else
        format.html { render action: "new" }
        format.json { render json: @base_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /base_urls/1
  # PUT /base_urls/1.json
  def update
    @base_url = BaseUrl.find(params[:id])

    respond_to do |format|
      if @base_url.update_attributes(params[:base_url])
        format.html { redirect_to @base_url, notice: 'Base url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @base_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_urls/1
  # DELETE /base_urls/1.json
  def destroy
    @base_url = BaseUrl.find(params[:id])
    @base_url.destroy

    respond_to do |format|
      format.html { redirect_to base_urls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/base_urls_helper.rb
module BaseUrlsHelper
end

app/views/base_urls/_form.html.erb
<%= form_for(@base_url) do |f| %>
  <% if @base_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@base_url.errors.count, "error") %> prohibited this base_url from being saved:</h2>

      <ul>
      <% @base_url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_url %><br />
    <%= f.text_field :page_url %>
  </div>
  <div class="field">
    <%= f.label :common_url %><br />
    <%= f.text_field :common_url %>
  </div>
  <div class="field">
    <%= f.label :base %><br />
    <%= f.text_field :base %>
  </div>
  <div class="field">
    <%= f.label :sourcetype %><br />
    <%= f.select :sourcetype, ['','job_by_row'] %>
  </div>
  <div class="field">
    <%= f.label :jobrowcss %><br />
    <%= f.text_field :jobrowcss %>
  </div>
   <div class="field">
    <%= f.label :titlecss %><br />
    <%= f.text_field :titlecss %>
  </div>
  <div class="field">
    <%= f.label :companycss %><%= f.text_field :companycss %> or <%= f.label :company0 %><%= f.text_field :company0 %>
  </div>
  <div class="field">
    <%= f.label :comptype %><%= f.text_field :comptype %>
  </div>
  <div class="field">
    <%= f.label :locationcss %><%= f.text_field :locationcss %> or <%= f.label :location0 %><%= f.text_field :location0 %>
  </div>
  <div class="field">
    <%= f.label :descriptioncss %><%= f.text_field :descriptioncss %>
  </div>
  <div class="field">
    <%= f.label :requirementcss %><%= f.text_field :requirementcss %> or<%= f.label :requirement0 %><%= f.text_field :requirement0 %>
  </div>
  <div class="field">
    <%= f.label :availabilitycss %><%= f.text_field :availabilitycss %> and <%= f.label :avail0 %><%= f.text_field :avail0 %>
  </div>
  <div class="field">
    <%= f.label :jobtypecss %><%= f.text_field :jobtypecss %> or <%= f.label :jobtype0 %><%= f.text_field :jobtype0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_urls/edit.html.erb
<h1>Editing base_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @base_url %> |
<%= link_to 'Back', base_urls_path %>

app/views/base_urls/index.html.erb
<h1>Listing base_urls</h1>

<table>
  <tr>
    <th>Page url</th>
    <th>Common url</th>
    <th>Base</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @base_urls.each do |base_url| %>
  <tr>
    <td><%= base_url.page_url %></td>
    <td><%= base_url.availabilitycss %></td>
    <td><%= link_to 'Show', base_url %></td>
    <td><%= link_to 'Edit', edit_base_url_path(base_url) %></td>
    <td><%= link_to 'Destroy', base_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Base url', new_base_url_path %>

app/views/base_urls/new.html.erb
<h1>New base_url</h1>

<%= render 'form' %>

<%= link_to 'Back', base_urls_path %>

app/views/base_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Page url:</b>
  <%= @base_url.page_url %>
</p>

<p>
  <b>Common url:</b>
  <%= @base_url.common_url %>
</p>

<p>
  <b>Base:</b>
  <%= @base_url.base %>
</p>


<%= link_to 'Edit', edit_base_url_path(@base_url) %> |
<%= link_to 'Back', base_urls_path %>